name = "lumesonic"
compatibility_date = "2024-01-15"
pages_build_output_dir = "./dist"

[env.production]
name = "lumesonic"

[[env.production.routes]]
pattern = "*"
zone_name = "lumesonic"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = "./dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 